apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-00-e648fdcf8987/my-repository/sample-app:v1.0
        ports:
        - containerPort: 8080
        tier: production
